# Generated by Django 5.0.7 on 2024-08-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_blockedips_remove_customuser_email_failedlogintry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, verbose_name='شماره تماس'),
        ),
    ]
